export const SET_BREWERIES = 'SET_BREWERIES'
export const GET_BREWERY = 'GET_BREWERY'

export const DRAWER_TOGGLED = 'DRAWER_TOGGLED'

export const SEARCH_STREET_ADDRESS_UPDATED = 'SEARCH_STREET_ADDRESS_UPDATED'
export const SEARCH_STREET_ADDRESS_FAILED = 'SEARCH_STREET_ADDRESS_FAILED'

export const SEARCH_COORDS_UPDATED = 'SEARCH_COORDS_UPDATED'
export const SEARCH_COORDS_FAILED = 'SEARCH_COORDS_FAILED'

export const CURRENT_POSITION = 'CURRENT_POSITION'
export const CURRENT_POSITION_FAILED = 'CURRENT_POSITION_FAILED'
